### ISSUE TITLE
Default setting motion or touchpad option

### ISSUE THREAD

**Issue by thenaturalone** [mahad-ahmed/Air-Mouse-Server#4]
Consider adding a settings option to force the Android AirMouse to start in the choice of Motion OR Touchpad automatically on startup, so that when the app is started it could go directly to touchpad, with one less click (instead of having to manually top touchpad every time one starts the app)?

**Comment by mahad-ahmed** [comment]
So you want it to go to the last used mode? I've been meaning to do that for a while now. I'll add it in the next update hopefully.

**Comment by mahad-ahmed** [comment]
Done. Update v5.0.4+ will automatically select the last selected mode(touchpad/motion). If you have any further problems, please open another issue.

Note: Please allow up to around 48 hours for the update to be live on the Play Store.
